[SPARK-47215][CORE][TESTS] Reduce the number of required threads in `MasterSuite`
### What changes were proposed in this pull request?

This PR aims to reduce the umber of required threads in `MasterSuite` test.

### Why are the changes needed?

- https://github.com/apache/spark/actions/workflows/build_maven_java21_macos14.yml
  - https://github.com/apache/spark/actions/runs/8070641575/job/22086547398
```
- SPARK-46881: scheduling with workerSelectionPolicy - CORES_FREE_ASC (true)
- SPARK-46881: scheduling with workerSelectionPolicy - CORES_FREE_ASC (false)
Warning: [3943.730s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 4096k, guardsize: 16k, detached.
Warning: [3943.730s][warning][os,thread] Failed to start the native thread for java.lang.Thread "rpc-server-13566-3"
Warning: [3943.730s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 4096k, guardsize: 16k, detached.
Warning: [3943.730s][warning][os,thread] Failed to start the native thread for java.lang.Thread "globalEventExecutor-3-961"
*** RUN ABORTED ***
An exception or error caused a run to abort: unable to create native thread: possibly out of memory or process/resource limits reached
  java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #45320 from dongjoon-hyun/SPARK-47215.

Authored-by: Dongjoon Hyun <dhyun@apple.com>
Signed-off-by: Dongjoon Hyun <dhyun@apple.com>