[SPARK-46077][SQL] Consider the type generated by TimestampNTZConverter in JdbcDialect.compileValue
### What changes were proposed in this pull request?

Considering the following case

```
./bin/spark-shell --packages org.postgresql:postgresql:9.4.1211 --conf spark.sql.timestampType=TIMESTAMP_NTZ

spark.sql("create table tz3 using jdbc options('url' 'jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres', 'dbtable' 'public.tz', 'driver' 'org.postgresql.Driver', 'preferTimestampNTZ' 'true') as select 1 as id, to_timestamp('2021-04-01 00:00:00', 'yyyy-MM-dd HH:mm:ss') as ts")

spark.sql("select * from tz3 where ts=to_timestamp('2021-04-01 00:00:00', 'yyyy-MM-dd HH:mm:ss')").show

```

The generated query is incorrect because the literal is not quoted

```
ERROR:  syntax error at or near "T00" at character 81
STATEMENT:  SELECT "id","ts" FROM public.tz  WHERE ("ts" IS NOT NULL) AND ("ts" = 2021-04-01T00:00)

```
TimestampNTZConverter generates a LocalDateTime value that we do not consider in JdbcDialect.compileValue

### Why are the changes needed?

It solves the bug explained

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

With unit tests and manually

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #45261 from planga82/bugfix/spark46077_ntz.

Authored-by: Pablo Langa <soypab@gmail.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>